### ISSUE TITLE
A few suggestions

### ISSUE THREAD

**Issue by tipsy** [chadmorrow/reactform#1]
Hi Chad, happy to see you've finished this. I had a quick look through the code and noticed a few things: 

* The default port is actually 7000, not 8080. You can remove the highlighted section, or at least the comment: https://github.com/chadmorrow/reactform/blob/master/reactform-server/src/main/kotlin/javalin-server.kt#L18-L21
* `ctx.result(JSON.stringify(HelloWorld()))` would be nicer as `ctx.json(HelloWorld())`, this used to require Jackson, but you can configure Javalin to use `kotlinx.serialization.json.JSON` if that's important.
* The comment at the end seems to be a little out of sync (what PUT?): https://github.com/chadmorrow/reactform/blob/master/reactform-server/src/main/kotlin/javalin-server.kt#L24-L33
* Javalin 1.7.0 is available now. 

Now this part is very subjective, but I think it would be more readable if you separated the comment from the Javalin server config:

```
/*
 We can create a server almost like in express.js.
 We set the port to 7000 and enable CORS for all origins (consider if this is suitable
 for your app before enabling it in production)
*/
val app = Javalin.create().apply {
    port(7000)
    enableCorsForOrigin("*")
}.start()
```

Enabling CORS is in generally not a security risk, so I don't think you have to say that they MUST change it.

**Comment by stacygrace** [comment]
Well this is what happens when you make last minute changes to month-old code that you don't think will affect anything substantially.  Thank you for pointing all that out! 

I'm stumped on what I was thinking when I mentioned the port number.  Will definitely remove that comment. I hadn't noticed the Kotlin Serialization support when I set this up and will happily change that to use ctx.json. As for the PUT route, wow. I changed an even more outdated comment before pushing the repo up and must have nuked the route entirely when I did so. Quality attention to detail on my part.

The other thing I'm baffled by (_seriously, what joker wrote this code?_) is the Cors setting. I'm pretty sure I added that when I was having a lot of difficulties getting the fetch api to work in the client side of things. Chrome was hassling me and I thought for a while it was because of cross origin issues. Not sure why the comment is so strident about changing it.

Thank you again for bringing these things up. I'll make some changes and make sure its more presentable before I start building out additional functionality.

EDIT - nope, I was wrong about the PUT route. The POST route that's currently there started life as PUT because of a mistake and then in another show of quality attention to detail, I missed that I'd never fixed the comment.

**Comment by stacygrace** [comment]
One more thing! 

This is definitely not finished by any means. This is an extremely bare bones version that I only decided to put out in its current form because it helped answer some questions about how to get started with kotlin on the front end. I'm going to be putting a lot more into this later!

**Comment by tipsy** [comment]
Cool! I'm going on vacation for a bit, but I'll check out the project when I get back.

**Comment by stacygrace** [comment]
Its not entirely clear to me how to tell Javalin to use kotlin serialization instead of jackson. Think that's the only thing left to clean up of the original commit.

**Comment by tipsy** [comment]
Sorry @chadmorrow, I was traveling. Here is an example using GSON: 

```
JavalinJsonPlugin.jsonToObjectMapper = object : JsonToObjectMapper {
    override fun <T> map(json: String, targetClass: Class<T>): T {
        return gson.fromJson(json, targetClass)
    }
}

JavalinJsonPlugin.objectToJsonMapper = object : ObjectToJsonMapper {
    override fun map(obj: Any): String {
        return gson.toJson(obj)
    }
}
```

Kotlin doesn't always win, the example looks a lot nicer in Java: 

```
Gson gson = new GsonBuilder().create();
JavalinJsonPlugin.setJsonToObjectMapper(gson::fromJson);
JavalinJsonPlugin.setObjectToJsonMapper(gson::toJson);
```

I guess the code is a bit advanced, maybe it's better to stick to your current approach?

**Comment by stacygrace** [comment]
Well, I'm going to throw in the towel on figuring out how to make the kotlinx serialization library work with the JavalinJsonPlugin. I think for now I'll leave it as is and then revisit it later. Thanks for the feedback!
